# -*- coding: utf-8 -*-
# Generated by Django 1.9b1 on 2016-02-01 20:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('faq', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='questioncategory',
            options={'verbose_name': 'category', 'verbose_name_plural': 'categories'},
        ),
    ]
