# -*- coding: utf-8 -*-
# Generated by Django 1.9b1 on 2016-02-03 10:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faq', '0002_auto_20160201_2111'),
    ]

    operations = [
        migrations.AddField(
            model_name='questioncategory',
            name='emoji_alt',
            field=models.CharField(blank=True, max_length=5),
        ),
    ]
