# -*- coding: utf-8 -*-
# Generated by Django 1.9b1 on 2016-01-22 11:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('speakers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='speaker',
            name='is_keynote',
            field=models.BooleanField(default=False),
        ),
    ]
