# -*- coding: utf-8 -*-
# Generated by Django 1.9b1 on 2016-01-22 11:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('speakers', '0002_speaker_is_keynote'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='speaker',
            name='confirmed',
        ),
    ]
