# -*- coding: utf-8 -*-
# Generated by Django 1.9b1 on 2016-02-03 17:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('speakers', '0003_remove_speaker_confirmed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='speaker',
            name='twitter',
            field=models.CharField(blank=True, help_text="Don't include any leading @", max_length=50),
        ),
    ]
