# -*- coding: utf-8 -*-
# Generated by Django 1.9b1 on 2016-02-03 18:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('speakers', '0004_auto_20160203_1857'),
    ]

    operations = [
        migrations.AddField(
            model_name='speaker',
            name='mentoring',
            field=models.BooleanField(default=False),
        ),
    ]
