# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-12 09:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import speakers.models


class Migration(migrations.Migration):

    dependencies = [
        ('speakers', '0005_speaker_mentoring'),
    ]

    operations = [
        migrations.CreateModel(
            name='Talk',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateField(default=speakers.models.get_talk_default_date)),
                ('start', models.TimeField(default=speakers.models.get_talk_default_start)),
                ('end', models.TimeField()),
                ('_description', models.TextField(blank=True)),
                ('speaker', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='speakers.Speaker')),
            ],
            options={
                'ordering': ('day', 'start'),
            },
        ),
    ]
