# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-15 12:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('speakers', '0006_talk'),
    ]

    operations = [
        migrations.AddField(
            model_name='talk',
            name='_author',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='talk',
            name='_title',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
