# -*- coding: utf-8 -*-
# Generated by Django 1.9b1 on 2016-01-11 15:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scholarships', '0003_auto_20160111_1606'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='python_django',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
