# -*- coding: utf-8 -*-
# Generated by Django 1.9b1 on 2015-11-29 21:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cfp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposal',
            name='mentoring',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='proposal',
            name='notes',
            field=models.TextField(blank=True),
        ),
    ]
