# -*- coding: utf-8 -*-
# Generated by Django 1.9b1 on 2015-11-29 22:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cfp', '0002_auto_20151129_2251'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proposal',
            name='skill_level',
            field=models.PositiveIntegerField(choices=[(1, ''), (2, 'novice'), (3, 'intermediate'), (4, 'advanced'), (5, 'everyone')], default=1),
        ),
    ]
