# -*- coding: utf-8 -*-
# Generated by Django 1.9b1 on 2015-11-30 10:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cfp', '0003_auto_20151129_2357'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proposal',
            name='skill_level',
            field=models.PositiveIntegerField(choices=[(1, 'everyone'), (2, 'novice'), (3, 'intermediate'), (4, 'advanced')], default=1),
        ),
    ]
