# -*- coding: utf-8 -*-
# Generated by Django 1.9b1 on 2016-01-20 16:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cfp', '0004_auto_20151130_1103'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposal',
            name='selected',
            field=models.BooleanField(default=False),
        ),
    ]
