# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-15 12:40
from __future__ import unicode_literals

from django.db import migrations, models
import schedule.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Workshop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateField(default=schedule.models.get_talk_default_date)),
                ('start', models.TimeField(default=schedule.models.get_talk_default_start)),
                ('end', models.TimeField()),
                ('_title', models.CharField(blank=True, max_length=200)),
                ('_description', models.TextField(blank=True)),
                ('_author', models.CharField(blank=True, max_length=200)),
            ],
            options={
                'abstract': False,
                'ordering': ('day', 'start'),
            },
        ),
    ]
