# -*- coding: utf-8 -*-
# Generated by Django 1.9b1 on 2016-01-13 15:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sponsor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('bronze', 'Bronze'), ('silver', 'Silver'), ('gold', 'Gold'), ('Platinum', 'Platinum')], max_length=20)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, help_text="Use `[[link text]]` to create a link to the sponsor's URL.")),
                ('logo', models.ImageField(blank=True, upload_to='sponsors/%Y/')),
                ('url', models.URLField(blank=True)),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('is_live', models.BooleanField(default=False)),
                ('paid', models.BooleanField(default=False)),
            ],
        ),
    ]
