# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-01 23:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sponsors', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sponsor',
            name='level',
            field=models.CharField(choices=[('bronze', 'Bronze'), ('silver', 'Silver'), ('gold', 'Gold'), ('Platinum', 'Platinum'), ('partner', 'Partner')], max_length=20),
        ),
    ]
